'use client';
import {useEffect,useState} from 'react';
import {Download,Save,Check,X,Trash2} from 'lucide-react';
import {AlertDialog,AlertDialogAction,AlertDialogCancel,AlertDialogContent,AlertDialogDescription,AlertDialogFooter,AlertDialogHeader,AlertDialogTitle,AlertDialogTrigger} from '@/components/ui/alert-dialog';
import {Progress} from '@/components/ui/progress';
type Segment={start:number;end:number;text:string;translation:string};
export default function Project({job,lang,changed,deleted}:{job:any;lang:string;changed:(j:any)=>void;deleted:()=>void}){
 const t=(a:string,b:string)=>lang==='my'?b:a;
 const [segments,S]=useState<Segment[]>([]),[dirty,D]=useState(false),[busy,B]=useState(false),[error,E]=useState('');
 useEffect(()=>{if(job.segments){S(job.segments);D(false)}else if(['review','completed'].includes(job.status)){fetch('/api/jobs/'+job.id).then(r=>r.json()).then((d:any)=>{if(d.job?.segments){S(d.job.segments);changed(d.job)}}).catch(()=>{})}},[job.id,job.revision,job.status]);
 async function action(path='',method='POST',body?:unknown){B(true);E('');try{const r=await fetch('/api/jobs/'+job.id+path,{method,headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const d:any=await r.json();if(!r.ok)throw Error(d.error||d.detail||'Request failed');if(d.job){changed(d.job);D(false)}if(d.deleted)deleted()}catch(e){E((e as Error).message)}finally{B(false)}}
 const labels:Record<string,string[]>={awaiting_worker:['Waiting for notebook — run one cell in your selected backend','Notebook စောင့်နေသည် — ရွေးထားသော backend တွင် cell ကို run ပါ'],queued:['Queued','စောင့်ဆိုင်းနေသည်'],extracting:['Reading audio','အသံထုတ်ယူနေသည်'],separating:['Separating speech','စကားသံ ခွဲထုတ်နေသည်'],transcribing:['Transcribing','စာသားပြောင်းနေသည်'],translating:['Translating','ဘာသာပြန်နေသည်'],exporting:['Preparing subtitles','စာတန်း ပြင်ဆင်နေသည်'],review:['Ready for review','စစ်ဆေးရန် အသင့်'],rendering:['Rendering video','ဗီဒီယို ထုတ်လုပ်နေသည်'],completed:['Completed','ပြီးစီးပါပြီ'],failed:['Needs attention','စစ်ဆေးရန် လိုအပ်သည်'],cancelled:['Cancelled','ပယ်ဖျက်ပြီး']};
 const terminal=['review','completed','failed','cancelled'].includes(job.status);
 return <section className="job-panel"><div className="section-title"><h2>{job.name}</h2><span className="muted">{(labels[job.status]||[job.status,job.status])[lang==='my'?1:0]}</span></div><Progress value={job.progress}/>{job.error&&<p role="alert">{job.error}</p>}{segments.length>0&&terminal&&<><div className="editor-heading"><h3>{t('Review subtitles','စာတန်းများ စစ်ဆေးရန်')}</h3><span>{segments.length} {t('segments','စာကြောင်း')}</span></div><div className="subtitle-editor">{segments.map((s,i)=><div className="subtitle-row" key={i}><div className="timing">{String(i+1).padStart(2,'0')}<br/>{s.start.toFixed(2)} – {s.end.toFixed(2)}s</div><p>{s.text}</p><label className="sr-only" htmlFor={'cue-'+i}>{t('Translation','ဘာသာပြန်')} {i+1}</label><textarea id={'cue-'+i} value={s.translation} maxLength={4000} onChange={e=>{S(old=>old.map((v,n)=>n===i?{...v,translation:e.target.value}:v));D(true)}}/></div>)}</div><div className="project-actions"><button className="secondary-button" disabled={!dirty||busy} onClick={()=>action('','PATCH',{revision:job.revision,segments})}><Save size={16}/>{t('Save changes','ပြင်ဆင်မှု သိမ်းရန်')}</button><button className="primary-button" disabled={dirty||busy} onClick={()=>action('/render')}><Check size={16}/>{t('Approve & export','အတည်ပြုပြီး ထုတ်ယူရန်')}</button></div><div className="downloads">{['subtitles.srt','subtitles.vtt','segments.json',...(job.status==='completed'&&job.options?.burn?['output.mp4']:[])].map(name=><a key={name} href={'/api/jobs/'+job.id+'/files/'+name}><Download size={15}/>{name}</a>)}</div></>}{job.status==='failed'&&<button className="secondary-button" disabled={busy} onClick={()=>action('/retry')}>{t('Retry project','ပြန်လည် လုပ်ဆောင်ရန်')}</button>}{!terminal&&<button className="secondary-button" disabled={busy} onClick={()=>action('/cancel')}><X size={16}/>{t('Cancel processing','လုပ်ဆောင်မှု ပယ်ဖျက်ရန်')}</button>}{terminal&&<AlertDialog><AlertDialogTrigger asChild><button className="text-link delete-button" disabled={busy}><Trash2 size={15}/>{t('Delete project','ပရောဂျက် ဖျက်ရန်')}</button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{t('Delete this project?','ပရောဂျက်ကို ဖျက်မည်လား။')}</AlertDialogTitle><AlertDialogDescription>{t('The video, subtitles and exports will be permanently removed.','ဗီဒီယို၊ စာတန်းနှင့် ထုတ်ယူထားသော ဖိုင်များကို အပြီးတိုင် ဖျက်ပါမည်။')}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>{t('Keep project','မဖျက်တော့ပါ')}</AlertDialogCancel><AlertDialogAction onClick={()=>action('','DELETE')}>{t('Delete project','ဖျက်ရန်')}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>}{error&&<p role="alert">{error}</p>}</section>
}
