"use client";
import {useEffect,useRef,useState} from 'react';
import {AudioLines,Languages,Film,CloudUpload,ArrowRight,ShieldCheck,Settings2,Workflow,Subtitles,Check,X} from 'lucide-react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Switch} from '@/components/ui/switch';
import {Progress} from '@/components/ui/progress';
import Connections from '@/components/studio/connections';
import Project from '@/components/studio/project';
type Job={id:string;name:string;status:string;progress:number;error?:string};
function Choice({label,value,set,items}:{label:string;value:string;set:(s:string)=>void;items:string[][]}){return <label className="field"><span>{label}</span><Select value={value} onValueChange={set}><SelectTrigger className="choice"><SelectValue/></SelectTrigger><SelectContent>{items.map(([v,t])=><SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select></label>}
export default function Home(){
 const [lang,L]=useState('en'),[tab,T]=useState('studio'),[file,F]=useState<File|null>(null),[url,U]=useState(''),[source,S]=useState('auto'),[target,G]=useState('my'),[provider,P]=useState('omniroute'),[execution,V]=useState('modal'),[sep,Q]=useState(false),[burn,B]=useState(true),[notice,N]=useState(''),[busy,Y]=useState(false),[ready,R]=useState(false),[jobs,J]=useState<Job[]>([]),[job,K]=useState<Job|null>(null);const input=useRef<HTMLInputElement>(null);const t=(a:string,b:string)=>lang==='my'?b:a;
 useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!context)return;const life=new AbortController();Promise.resolve(context.registerTool({name:'open_studio_view',description:'Open the translation studio, projects list or connections settings. Does not submit videos or change credentials.',inputSchema:{type:'object',properties:{view:{type:'string',enum:['studio','jobs','settings']}},required:['view'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{const view=(input as {view?:string})?.view;if(!view||!['studio','jobs','settings'].includes(view))throw Error('Invalid view');T(view);return {view}}},{signal:life.signal})).catch(()=>{});return()=>life.abort()},[]);
 useEffect(()=>{L(localStorage.getItem('vt-language')||'en');fetch('/api/status').then(r=>r.json()).then((d:any)=>R(!!d.ready)).catch(()=>{});fetch('/api/jobs').then(r=>r.json()).then((d:any)=>J(d.jobs||[])).catch(()=>{})},[]);
 useEffect(()=>{document.documentElement.lang=lang;localStorage.setItem('vt-language',lang)},[lang]);
 useEffect(()=>{if(!file){U('');return}const u=URL.createObjectURL(file);U(u);return()=>URL.revokeObjectURL(u)},[file]);
 useEffect(()=>{if(!job||['review','completed','failed','cancelled'].includes(job.status))return;const id=setInterval(()=>fetch('/api/jobs/'+job.id).then(r=>r.json()).then((d:any)=>{if(d.job){K(d.job);J(old=>old.map(j=>j.id===d.job.id?d.job:j))}}).catch(()=>{}),4000);return()=>clearInterval(id)},[job?.id,job?.status]);
 function choose(f?:File){if(!f)return;if(f.size>=100000000){N(t('Choose a video smaller than 100 MB.','100 MB အောက် ဗီဒီယိုကို ရွေးပါ။'));return}if(!/\.(mp4|mov|mkv|webm)$/i.test(f.name)){N('Supported formats: MP4, MOV, MKV, WebM.');return}F(f);N('')}
 async function start(){if(!file)return;Y(true);try{const encode=(s:string)=>btoa(String.fromCharCode(...new TextEncoder().encode(s))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');const r=await fetch('/api/jobs',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Video-Name':encode(file.name),'X-Video-Options':encode(JSON.stringify({source,target,provider,separate:sep,burn,execution})),'X-Request-Id':crypto.randomUUID().replaceAll('-','')},body:file});const b:any=await r.json();if(!r.ok)throw Error(b.error||b.detail||'Upload failed');K(b.job);J(old=>[b.job,...old])}catch(e){N((e as Error).message)}finally{Y(false)}}
 return <main><header className="topbar"><a className="brand" href="/"><span className="brand-icon"><AudioLines/></span>VideoTrans <b>Studio</b></a><div className="top-actions"><span className="private-label"><ShieldCheck size={16}/>{t('Private workspace','သီးသန့် အလုပ်ခန်း')}</span><button className="language-button" onClick={()=>L(lang==='en'?'my':'en')}><Languages size={17}/>{lang==='en'?'မြန်မာ':'English'}</button></div></header><div className="workspace"><div className="page-heading"><div><p className="eyebrow">VIDEO → LANGUAGE → CONNECTION</p><h1>{t('Your video. Another language.','သင့်ဗီဒီယိုကို ဘာသာစကားအသစ်ဖြင့်')}</h1><p>{t('Transcribe, translate and create subtitles in one workspace.','အသံကို စာသားပြောင်း၊ ဘာသာပြန်ပြီး စာတန်းထိုး ဖန်တီးပါ။')}</p></div><span className="model-chip"><AudioLines size={16}/>Whisper large-v3</span></div>
 <Tabs value={tab} onValueChange={T}><TabsList className="main-tabs" variant="line"><TabsTrigger value="studio"><Film/>{t('Translation studio','ဘာသာပြန် အလုပ်ခန်း')}</TabsTrigger><TabsTrigger value="jobs"><Workflow/>{t('Projects','ပရောဂျက်များ')}<span className="count">{jobs.length}</span></TabsTrigger><TabsTrigger value="settings"><Settings2/>{t('Connections','ချိတ်ဆက်မှုများ')}</TabsTrigger></TabsList>
 <TabsContent value="studio"><div className="studio-grid"><section className="source-panel"><div className="section-title"><span className="step">01</span><h2>{t('Source video','မူရင်း ဗီဒီယို')}</h2><span className="muted">{t('Start here','ဤနေရာမှ စတင်ပါ')}</span></div>{!file?<button className="dropzone" onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();choose(e.dataTransfer.files[0])}}><span className="upload-icon"><CloudUpload size={34} strokeWidth={1.5}/></span><strong>{t('Drop your video here','ဗီဒီယိုကို ဤနေရာတွင် ထည့်ပါ')}</strong><span>{t('or click to browse your files','သို့မဟုတ် ဖိုင်ရွေးရန် နှိပ်ပါ')}</span><div className="file-types">MP4 · MOV · MKV · WEBM</div><span className="limits">{t('Under 10 minutes · Under 100 MB','၁၀ မိနစ်အောက် · 100 MB အောက်')}</span></button>:<div className="video-card"><video src={url} controls onLoadedMetadata={e=>{if(e.currentTarget.duration>=600){F(null);N(t('Videos must be shorter than 10 minutes.','ဗီဒီယိုသည် ၁၀ မိနစ်အောက် ဖြစ်ရပါမည်။'))}}}/><div className="file-info"><Film/><div><strong>{file.name}</strong><p>{(file.size/1e6).toFixed(1)} MB</p></div><button aria-label="Remove video" onClick={()=>F(null)}><X size={18}/></button></div></div>}<input hidden ref={input} type="file" accept=".mp4,.mov,.mkv,.webm" onChange={e=>choose(e.target.files?.[0])}/><div className="privacy-note"><ShieldCheck size={17}/>{t('Private files · Deleted automatically in 24–30 hours.','သီးသန့်ဖိုင်များ · ၂၄–၃၀ နာရီအတွင်း ဖျက်ပါသည်။')}</div><div className="pipeline"><p className="eyebrow">{t('THE WORKFLOW','လုပ်ဆောင်မှု အဆင့်များ')}</p><div><span><AudioLines size={20}/>{t('Transcribe','စာသားပြောင်း')}</span><ArrowRight size={16}/><span><Languages size={20}/>{t('Translate','ဘာသာပြန်')}</span><ArrowRight size={16}/><span><Subtitles size={20}/>{t('Export','ထုတ်ယူ')}</span></div></div></section>
 <section className="settings-panel"><div className="section-title"><span className="step">02</span><h2>{t('Make it yours','ဘာသာပြန် ဆက်တင်များ')}</h2></div><div className="language-grid"><Choice label={t('Original language','မူရင်း ဘာသာစကား')} value={source} set={S} items={[["auto",t('Auto-detect','အလိုအလျောက်')],["en","English"],["my","မြန်မာ"]]}/><Choice label={t('Translate into','ဘာသာပြန်ရန်')} value={target} set={G} items={[["my","မြန်မာ · Burmese"],["en","English"]]}/></div><Choice label={t('Translation provider','ဘာသာပြန် ဝန်ဆောင်မှု')} value={provider} set={P} items={[["omniroute","OmniRoute"],["freellmapi","FreeLLMAPI"]]}/><Choice label={t("Processing backend","လုပ်ဆောင်မည့် backend")} value={execution} set={V} items={[["modal",t("Modal · Automatic","Modal · အလိုအလျောက်")],["colab","Colab · Notebook"],["kaggle","Kaggle · Notebook"],["lightning","Lightning AI · Worker"]]}/><div className="divider"/><div className="option"><div><strong>{t('Isolate speech','စကားသံ သီးခြားခွဲထုတ်ရန်')}</strong><p>{t('Separate vocals with MVSEP before transcription.','စာသားမပြောင်းမီ MVSEP ဖြင့် စကားသံ ခွဲထုတ်ပါ။')}</p></div><Switch checked={sep} onCheckedChange={Q} aria-label="Isolate speech"/></div><div className="option"><div><strong>{t('Subtitled video','စာတန်းထိုး ဗီဒီယို')}</strong><p>{t('Burn translated subtitles into your video.','ဘာသာပြန် စာတန်းကို ဗီဒီယိုတွင် ထည့်ပါ။')}</p></div><Switch checked={burn} onCheckedChange={B} aria-label="Burn subtitles"/></div><div className="export-note"><Check size={16}/>{t('SRT + VTT subtitles included with every project','SRT နှင့် VTT စာတန်းဖိုင်များ ပါဝင်သည်')}</div>{!ready&&<button className="setup-note" onClick={()=>T('settings')}><Settings2 size={17}/>{t('Connect your processing backend to begin','စတင်ရန် backend ကို ချိတ်ဆက်ပါ')}<ArrowRight size={16}/></button>}<button className="primary-button" disabled={!file||busy||!ready} onClick={start}>{busy?t('Uploading…','တင်နေသည်…'):t('Create translation','ဘာသာပြန် စတင်ရန်')}<ArrowRight size={18}/></button><p className="footnote">{t('Review and edit your subtitles before the final export.','နောက်ဆုံး ထုတ်ယူမီ စာတန်းများကို စစ်ဆေး၊ ပြင်ဆင်နိုင်ပါသည်။')}</p></section></div>{job&&<Project job={job} lang={lang} changed={j=>{K(j);J(old=>old.map(v=>v.id===j.id?j:v))}} deleted={()=>{J(old=>old.filter(v=>v.id!==job.id));K(null)}}/>}</TabsContent>
 <TabsContent value="jobs"><section className="panel"><h2>{t('Your projects','သင့် ပရောဂျက်များ')}</h2>{!jobs.length?<div className="empty"><Film size={36}/><h3>{t('Your first story starts here','သင့်ပထမ ပရောဂျက်ကို စတင်ပါ')}</h3><p>{t('Upload a video to create your first translation.','ပထမဆုံး ဘာသာပြန်ရန် ဗီဒီယိုတင်ပါ။')}</p><button className="secondary-button" onClick={()=>T('studio')}>{t('New translation','ဘာသာပြန် အသစ်')}</button></div>:jobs.map(j=><button className="job-row" key={j.id} onClick={()=>{K(j);T('studio')}}><Film/><strong>{j.name}</strong><span>{j.status}</span><ArrowRight size={18}/></button>)}</section></TabsContent>
 <TabsContent value="settings"><Connections lang={lang} onConnected={()=>fetch('/api/status').then(r=>r.json()).then((d:any)=>R(!!d.ready))}/></TabsContent></Tabs>{notice&&<div className="notice" role="alert">{notice}<button aria-label="Dismiss" onClick={()=>N('')}><X size={18}/></button></div>}<footer><span>VideoTrans Studio</span><span>{t('English & Burmese, connected.','အင်္ဂလိပ် နှင့် မြန်မာ')}</span></footer></div></main>
}
